# Generated by Django 2.2.6 on 2019-10-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='usuario',
            new_name='user',
        ),
    ]
